### ISSUE TITLE
add more ffmpeg filters

### ISSUE THREAD

**Issue by sugizo** [DedInc/vidspinner#3]
**objective** 
have more ffmpeg filters 

**ref**
https://ffmpeg.org/ffmpeg-filters.html

realize that user 
can use custom filter, 
but at least make all default preset available 
in vidspinner 
will make it conviniet
**e.g.**
```
pseudocolor = preset = shadows
pseudocolor = preset = highlights
curves = increase_contrast
curves = linear_contrast
curves = medium_contrast
curves = strong_contrast
etc
```

best regards

**Comment by DedInc** [comment]
if you know how, u can use custom filter:

e.g.
```python
montage_builder = MontageBuilder()
montage_builder.add_custom_filter('chromakey=0x00ff00:0.2:0.4', start_duration=10, end_duration=20)
montage_builder.build()
```
